services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Noviigod1!
      POSTGRES_DB: marketplace_blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: Dora
      MINIO_ROOT_PASSWORD: Noviigod1!
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: Dora
      RABBITMQ_DEFAULT_PASS: Noviigod1!
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  minio_data:
